<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows7.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLogic\BusinessLogic.csproj" />
    <ProjectReference Include="..\ConsoleApp\ConsoleApp.csproj" />
    <ProjectReference Include="..\SharedLabubu\SharedLabubu.csproj" />
    <ProjectReference Include="..\WinFormsApp\WinFormsApp.csproj" />
  </ItemGroup>

</Project>
