<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Npgsql" Version="6.0.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ConsoleApp\ConsoleApp.csproj" />
		<ProjectReference Include="..\DataAccessLayer\DataAccessLayer.csproj" />
		<ProjectReference Include="..\Presenter\Presenter.csproj" />
		<ProjectReference Include="..\WinFormsApp\WinFormsApp.csproj" />
	</ItemGroup>

</Project>
